import { Article, Author, Vote } from "./types";

export const mockAuthors: Author[] = [
  {
    id: "1",
    name: "Sarah Chen",
    bio: "Investigative journalist with 15 years of experience covering corporate corruption and financial crimes. Pulitzer Prize nominee.",
    avatar: "/avatars/sarah-chen.jpg",
    reputation: 95,
    articlesPublished: 47,
    totalVotes: 2847,
    joinedDate: "2023-01-15",
    walletAddress: "AS1qE8K4HaXE9jRhq6JGE7K8X9WfGXhE8q",
    verified: true,
  },
  {
    id: "2",
    name: "Marcus Rodriguez",
    bio: "Environmental journalist and photographer documenting climate change impacts across Latin America.",
    avatar: "/avatars/marcus-rodriguez.jpg",
    reputation: 88,
    articlesPublished: 32,
    totalVotes: 1923,
    joinedDate: "2023-03-22",
    walletAddress: "AS2qF9L5IbYF0kShr7KHF8L9Y0XgGYiF9r",
    verified: true,
  },
  {
    id: "3",
    name: "Dr. Amara Okafor",
    bio: "Medical journalist and former healthcare worker covering public health crises and pharmaceutical industry.",
    avatar: "/avatars/amara-okafor.jpg",
    reputation: 92,
    articlesPublished: 28,
    totalVotes: 2156,
    joinedDate: "2023-02-08",
    walletAddress: "AS3qG0M6JcZG1lTis8LIG9M0Z1YhHZjG0s",
    verified: true,
  },
];

export const mockArticles: Article[] = [
  {
    id: "1",
    title: "The Silicon Valley Bank Collapse: A Warning Ignored",
    subtitle:
      "How regulatory capture and risky investments brought down the tech industry's favorite bank",
    content: "Full article content...",
    excerpt:
      "An in-depth investigation into the regulatory failures and warning signs that led to the collapse of Silicon Valley Bank, exposing the fragility of our modern banking system.",
    coverImage: "/images/svb-collapse-cover.jpg",
    author: {
      id: "1",
      name: "Sarah Chen",
      bio: "Investigative journalist with 15 years of experience covering corporate corruption and financial crimes. Pulitzer Prize nominee.",
      avatar: "/avatars/sarah-chen.jpg",
      reputation: 95,
      articlesPublished: 47,
      totalVotes: 2847,
      joinedDate: "2023-01-15",
      walletAddress: "AS1qE8K4HaXE9jRhq6JGE7K8X9WfGXhE8q",
      verified: true,
    },
    publishedAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-15T10:00:00Z",
    readTime: 12,
    category: "Finance",
    tags: ["banking", "regulation", "silicon-valley", "financial-crisis"],
    verificationScore: 94,
    voteCount: 247,
    upvotes: 235,
    downvotes: 12,
    status: "verified",
    premium: true,
    price: 5.0,
    chapters: [
      {
        id: "ch1",
        title: "The Warning Signs",
        content:
          "In the months leading up to Silicon Valley Bank's spectacular collapse...",
        order: 1,
      },
      {
        id: "ch2",
        title: "The Fatal Miscalculation",
        content: "On March 8, 2023, Silicon Valley Bank announced...",
        order: 2,
      },
    ],
    stakingAmount: 50.0,
    ipfsHash: "QmX4Gx5y2H8K9w3E1R7T6U4I8O2P5Q9M3N7V1Z8B4C6D2",
    transactionHash: "0x1234567890abcdef...",
  },
  {
    id: "2",
    title: "The Amazon Rainforest Burns: A Climate Emergency Ignored",
    subtitle:
      "How political negligence and corporate greed are destroying the lungs of our planet",
    content: "Full article content...",
    excerpt:
      "A comprehensive investigation into the ongoing destruction of the Amazon rainforest and its implications for global climate change.",
    coverImage: "/images/amazon-fires-cover.jpg",
    author: {
      id: "2",
      name: "Marcus Rodriguez",
      bio: "Environmental journalist and photographer documenting climate change impacts across Latin America.",
      avatar: "/avatars/marcus-rodriguez.jpg",
      reputation: 88,
      articlesPublished: 32,
      totalVotes: 1923,
      joinedDate: "2023-03-22",
      walletAddress: "AS2qF9L5IbYF0kShr7KHF8L9Y0XgGYiF9r",
      verified: true,
    },
    publishedAt: "2024-01-12T14:30:00Z",
    updatedAt: "2024-01-12T14:30:00Z",
    readTime: 15,
    category: "Environment",
    tags: ["climate-change", "amazon", "deforestation", "environment"],
    verificationScore: 91,
    voteCount: 189,
    upvotes: 176,
    downvotes: 13,
    status: "verified",
    premium: true,
    price: 4.5,
    chapters: [],
    stakingAmount: 45.0,
    ipfsHash: "QmY5Hx6z3I9L0x4F2S8U7V5J9P3Q0N4M8W2A9C5E7G3H1",
    transactionHash: "0xabcdef1234567890...",
  },
  {
    id: "3",
    title: "The Opioid Crisis: Big Pharma's Deadly Deception",
    subtitle:
      "How pharmaceutical giants knowingly fueled America's deadliest drug epidemic",
    content: "Full article content...",
    excerpt:
      "An investigation into how pharmaceutical companies deliberately fueled the opioid epidemic, examining corporate deception, regulatory failure, and the ongoing fight for justice.",
    coverImage: "/images/opioid-crisis-cover.jpg",
    author: {
      id: "3",
      name: "Dr. Amara Okafor",
      bio: "Medical journalist and former healthcare worker covering public health crises and pharmaceutical industry.",
      avatar: "/avatars/amara-okafor.jpg",
      reputation: 92,
      articlesPublished: 28,
      totalVotes: 2156,
      joinedDate: "2023-02-08",
      walletAddress: "AS3qG0M6JcZG1lTis8LIG9M0Z1YhHZjG0s",
      verified: true,
    },
    publishedAt: "2024-01-10T09:15:00Z",
    updatedAt: "2024-01-10T09:15:00Z",
    readTime: 18,
    category: "Health",
    tags: ["opioids", "pharmaceutical", "public-health", "corporate-crime"],
    verificationScore: 96,
    voteCount: 312,
    upvotes: 298,
    downvotes: 14,
    status: "verified",
    premium: true,
    price: 6.0,
    chapters: [],
    stakingAmount: 60.0,
    ipfsHash: "QmZ6Iy7a4J0M1y5G3T9W8X6K0Q4R5S1O9B6D8F4H2J7L3",
    transactionHash: "0xfedcba0987654321...",
  },
];

export const mockVotes: Vote[] = [
  {
    id: "1",
    articleId: "1",
    voterId: "user1",
    voteType: "up",
    reason: "Well-researched and thoroughly documented",
    timestamp: "2024-01-15T12:30:00Z",
    stake: 10.0,
  },
  {
    id: "2",
    articleId: "1",
    voterId: "user2",
    voteType: "fact_check",
    reason: "Verified sources and cross-referenced claims",
    timestamp: "2024-01-15T14:45:00Z",
    stake: 25.0,
  },
];
